# Generated by Django 3.1.6 on 2021-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means_text', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vocab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocab_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('mean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.mean')),
            ],
        ),
        migrations.AddField(
            model_name='mean',
            name='vocab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocab'),
        ),
    ]
