# Generated by Django 3.1.6 on 2021-02-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vocab',
            new_name='Vocabs',
        ),
        migrations.RenameField(
            model_name='meaning',
            old_name='vocab',
            new_name='vocabs',
        ),
        migrations.RenameField(
            model_name='vocabs',
            old_name='vocab_text',
            new_name='vocabs_text',
        ),
    ]
