# Generated by Django 3.1.6 on 2021-02-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20210221_1656'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meaning',
            new_name='Means',
        ),
        migrations.RenameField(
            model_name='means',
            old_name='meaning_text',
            new_name='means_text',
        ),
    ]
