# Generated by Django 3.1.6 on 2021-02-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_auto_20210221_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Means',
        ),
        migrations.DeleteModel(
            name='Vocabs',
        ),
    ]
