# Generated by Django 3.1.6 on 2021-02-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_means_vocabs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Means',
        ),
        migrations.DeleteModel(
            name='Vocabs',
        ),
    ]
