# Generated by Django 3.1.6 on 2021-02-21 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vocab', '0006_auto_20210221_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vocabs_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Means',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('means_text', models.CharField(max_length=200)),
                ('vocabs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.vocabs')),
            ],
        ),
    ]
