# Generated by Django 3.1.6 on 2021-02-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_means_vocabs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Means',
            new_name='Mean',
        ),
        migrations.RenameModel(
            old_name='Vocabs',
            new_name='Vocab',
        ),
    ]
