# Generated by Django 3.1.6 on 2021-02-21 17:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_auto_20210221_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mean',
            old_name='vocabs',
            new_name='vocab',
        ),
        migrations.RemoveField(
            model_name='vocab',
            name='vocabs_text',
        ),
        migrations.AddField(
            model_name='vocab',
            name='vocab_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mean',
            name='means_text',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('mean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.mean')),
            ],
        ),
    ]
