# Generated by Django 3.1.6 on 2021-02-21 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_auto_20210221_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocab',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='vocab',
            name='means',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Mean',
        ),
    ]
