# Generated by Django 3.1.6 on 2021-02-16 12:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210215_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='votes_score',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 12, 12, 59, 389360, tzinfo=utc), verbose_name='time'),
        ),
    ]
