# Generated by Django 3.1.6 on 2021-02-16 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210216_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
